name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run actionlint
        uses: raven-actions/actionlint@v2
